// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using models;

#nullable disable

namespace Aura.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20241016062925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("models.Employee", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Departid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Employeeid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("models.EmployeeLeave", b =>
                {
                    b.Property<int>("Leaveid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Employeeid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Leaveid");

                    b.ToTable("EmployeeLeaves");
                });
#pragma warning restore 612, 618
        }
    }
}
